### ISSUE TITLE
[Todo] Fabric Crashlytics

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#100]
- [x] Add Fabric instead. https://fabric.io/kits/android/crashlytics/install
- [x] Check battery and network consumption of Answers, disable it if too high => **has been disabled**.
- [x] Check offline support.
- [x] Add Crashlytics.setString("VN_ID", vn.getId()) in VNDetailsActivity.
- [x] Add variables info in Crashlytics (size of lists...).
- [x] Remove the MailService, ErrorActivity and their interactions with CustomActivityOnCrash.
- [x] Remove the FeedbackActivity, replace it with a mail intent.
~~- [ ] Write a custom dialog prompt to replace CustomActivityOnCrash : http://stackoverflow.com/a/17218782/4561039~~

N.B.: Fabric is developed by Twitter so it's reliable in the long-term.

**Comment by herbeth1u** [comment]
Used with CustomActivityOnCrash, it has a non-optimal behavior: the CAOC still shows properly, but it kills the process and prevents Crashlytics from sending the bug report immediately (though Crashlytics CAN do it). The bug report is sent only when the app is restarted.
This is the best possible behavior using these 2 libs together, but it's not usable like so. As we have already encountered, the app already chain-crashed because of a problem in the sort algorithm. In this kind of cases, we absolutely need Crashlytics to be able to send the bug report immediately, instead of putting this in some kind of buffer and hoping that the next app execution will last long enough to send the report (which may never happen).

Anyway, with Crashlytics, CAOC became a heavy dependency just to show a pretty activity and tell the user that everything's under control. This is why:
- [ ] Remove CustomActivityOnCrash.

**Comment by herbeth1u** [comment]
Update: When launching the app in Debug mode but **without** the debugger, as of today, the app suddenly is able to send the Crashlytics report **and** displaying the CAOC. Also, since it's the _official_ way of mixing the two libs, let's do it like this for now. Sending a commit with this and keep monitoring the behavior.

**Comment by herbeth1u** [comment]
- [ ] Configure only for DEBUG.

**Comment by herbeth1u** [comment]
- [ ] Add Crashlytics reports for each printStackTrace().
