### ISSUE TITLE
[Todo] Refactoring [1]

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#13]
- [ ] Put the BaseAdapter somewhere in VNExpandableListAdapter in DatabaseStatisticsAdapter.
- [ ] Put VNDetailsActivity.onMenuItemClick in a VNDetailsController class.
- [ ] Put VNDetailsActivity.getExpandableListData in a VNDetailsFactory class.
