### ISSUE TITLE
[Todo] Redesign card layout 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#14]
- [x] Increase border radius 
- [x] Divider 
- [x] Include vote, wish, status 
- [x] Two-line ellipsized title
