### ISSUE TITLE
[Todo] Number of VNs

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#16]
- [x] Navigation drawer : number of VNs in vnlist, wishlist and votelist (right side).
- [x] Navigation drawer : remove all text above wallpaper and replace "My account" with the username.
- [x] Tab bar : number of VNs for each tab
