### ISSUE TITLE
[Todo] List sorting

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#17]
- [x] "Sort" button next to the "Filter" button.
- [x] Sorting by id, released date, vote, wish, status [...].
- [x] Remember the sorting state when the app restarts.
- [x] Make sure the lists are sorted after a loadData() or loadFromCache()
- [x] Add a " reverse" checkbox.

**Comment by herbeth1u** [comment]
Sorting the LinkedHashMap : 

Java-7 style : 
`List<Map.Entry<String, Integer>> entries =
  new ArrayList<Map.Entry<String, Integer>>(map.entrySet());
Collections.sort(entries, new Comparator<Map.Entry<String, Integer>>() {
  public int compare(Map.Entry<String, Integer> a, Map.Entry<String, Integer> b){
    return a.getValue().compareTo(b.getValue());
  }
});
Map<String, Integer> sortedMap = new LinkedHashMap<String, Integer>();
for (Map.Entry<String, Integer> entry : entries) {
  sortedMap.put(entry.getKey(), entry.getValue());
}`

Java 8-style : 
`map.entrySet().stream()
    .sorted(Map.Entry.comparingByValue())
    .forEach(entry -> ... );`

**Comment by herbeth1u** [comment]
Issue closed but make sure to monitor its behavior during test phase (performance of sorting algorithm, check that lists stay ordered if we change a VN on the fly, check that the order is okay even on big lists...).
