### ISSUE TITLE
[Todo] Spoilers

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#3]
- [x] Hide spoilery images and texts by default
- [x] Put a button somewhere on the VN details view to show spoilers
  - Button in action bar.
  - Displays a list (with/without radio buttons?) of spoiler levels.
  - On click : static spoilerLevel = x; VNDetailsActivity.recreate()
  - On finish() : spoilerLevel = SettingsManager.getSpoilerLevel()
  - Use VNDetailsActivity.spoilerLevel in Tag.checkSpoilerLevel()
- [x] Show spoilers only when status = completed (user option)
