### ISSUE TITLE
[Todo] Speed up login [2]

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#45]
Serializing cache variables in files seems to be slow. Consider a better approach.
- [x] Add a lot more VNs to the test account (~500 / 1000).
- [x] Check that all VNs appear in the application (cf. Play Store comment @ May 17 2016 08:42).
- [x] Benchmark the login speed with files (conversion to string + string serialization to file).
- [Abandoned] Create an SQLite db, 1 table per variable, 1 single record containing serialized JSON. Benchmark.
- [Abandoned] Create 1 record per entry in the db. Benchmark.
- Users complaining that login is too long : 
  - [x] check that internal storage does work properly on Android 4.2.
  - [x] Ask Yorhel to increase API limits.
- [x] Display a warning message somewhere in the login screen to warn the user the first connection may be long (up to 30s).
- [x] "throttled error" -> "You have issued too many requests recently. Please wait [...]" (type=cmd) / "The server is too busy to fulfill your request now. Please wait [...]"
- [Abandoned: Toast is sufficient] display a warning message somewhere to remember there was a throttled error during the first login and a refresh has to be done to display the remaining VNs (the refresh is in any case done at the next reboot).

**Comment by herbeth1u** [comment]
Results:
- Tested with 502 VNs on the test account.
  - VNs do appear properly in the application.
  - First connection time = 25s (36 queries)
  - Cached connection time = 3s (cache reading from file) + 2s (background update) = 5s
