### ISSUE TITLE
[Todo] Speed up login [3]

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#46]
Improve the cache's comparison algorithm and send "get vn" only for items that have actually changed, and not fetch all items again if only 1 has changed.

- [x] Remove "vnlist.clear()" after the "get vn" command.
- [x] Add "vnlist.removeKey(key)" for VNs that were in the cache but have been removed overtime. (The existing "vnlist.put()" code should already take care of modified and added VNs.)
- [x] Test and benchmark.
