### ISSUE TITLE
[Todo] Offline support 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#5]
- [x] Make all static fields in DB persistent : serialize to JSON -> save to file in INTERNAL storage (updated at each loadData() and before each VNDetailsActivity.finish())
- [x] Login : if connection KO and file in internal storage exists : deserialize from file to DB fields -> resume application flow
- [x] All operations afterwards, including " get ", " set " or " dbstats " : display an error message if no connection
- [x] Remove internal storage file when logging out. :)
- [ ] Add cache for "dbstats" and make sure it works offline and make sure it works if there's no cache for it.

**Comment by herbeth1u** [comment]
public static boolean isConnected(Context context) {
    ConnectivityManager connectivityManager = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
    NetworkInfo networkInfo = null;
    if (connectivityManager != null) {
        networkInfo = connectivityManager.getActiveNetworkInfo();
    }

    return networkInfo != null && networkInfo.getState() == NetworkInfo.State.CONNECTED;
}
