### ISSUE TITLE
[Todo] Search by tag

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#54]
Enable the search by tag, because the smart search unfortunately doesn't take the tags into account...
Think of a way to include this in the UI (or implicitly in the query?).

Next to the search bar, put a triple " : " button. On click, popover "Search options" with radio buttons ("Smart search" / "Search by tag" / ... more to come).

**Comment by herbeth1u** [comment]
Cannot "get vn" by tag yet ; ask Yorhel someday.

**Comment by herbeth1u** [comment]
@yorhel
> The api supports tag search as of yesterday

Planning this issue once again for 2.0.

**Comment by herbeth1u** [comment]
After some tests and (a lot of) efforts, splitwise/TokenAutoComplete seems to be able to handle the job.

- [ ] allowCollapse(true) bugs because the focus is messed up somehow. Write a hack to fix this.
- [ ] Not very convenient to type a tag when we're at the end of the line (seriously nobody's ever complained about this?). Write a hack to fix this.

**Comment by herbeth1u** [comment]
- [ ] Display tag's description upon long clicking on an auto-completion item.
- [ ] Add tags to a list so I can handle the search with them (at last!).
- [ ] Beautify the form with something (a lib? Or just a bit of talent in UI).
- [ ] Add a "help" button explaining how all of this works.

**Comment by herbeth1u** [comment]
- [ ] Remember the tags when the device is flipped.
- [ ] Implement "include all" / "include at least one".

**Comment by herbeth1u** [comment]
- [ ] Set auto-complete threshold to 1.
