### ISSUE TITLE
[Todo] Complete VN details 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#6]
- [x] Information 
  - [x] title 
  - [x] original 
  - [x] released 
  - [x] aliases 
  - [x] length 
  - [x] links (on click listener redirects to the link) 
- [x] Anime
  - [x] Title = title_romaji, subtitle = title_kanji \n type • year
  - [x] onclick = "https://anidb.net/perl-bin/animedb.pl?show=anime&aid=" + id
  - Ignore ann_id and nfo_id for the moment
- [x] Relations 
- [x] Stats 
  - [x] popularity (include a red-to-green bar as illustration) 
  - [x] rating + votecount 
- [x] Releases
  - [x] Put the API mutex INSIDE the thread so it doesn't block the UI if it has to wait! 
  - [x] Producers
  - [x] Modal on click
- [x] Characters 
  - [x] Representation identical to MAL's mobile interface.
  - [x] open character image in lightbox on click (image)
  - [x] open all character info in a modal on click (text)
  - [x] Use the traits dump to display characters' traits (recursive algorithm).
  - [x] Hide null / 0 values from the modal and improve formatting.
  - [x] Use new API tweak to display characters' roles.
