### ISSUE TITLE
[Todo] Optimization pt. 8 : load on click

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#63]
Don't load characters, releases and similar novels at startup to optimize time.
Fetch them when clicking on the corresponding submenu in the VN details view. Use the database to load only characters, releases or recommendations for the current VN.
If the characters are not in Cache.characters AND if the characters are not in the database, then fetch the characters from the API (if there's no connection then the error message will do).

- [x] Characters
- [x] Releases
- [x] Similar novels
- [x] All the other submenus!
- [x] Try to refactor inside an initSubmenu() method.
- [x] Find a way to remove from CHARACTER and RELEASE items that are not in any list (to lighten the database and speed it up). In loadData() maybe.
