### ISSUE TITLE
[Todo] Refresh VN's data

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#64]
As long as there is data in the database, we don't send an API query.
However the database does not have an expiration date, so to prevent out-of-date data : 

- [x] Pull to refresh VN's data on VNDetailsActivity : 
  - [x] Replace VNDetailsActivity.getTag with Cache.vns.get
  - [x] Send a "get vn" command
  - [x] Store it in database if needed (DB.saveVNs()) + removes all VN's data from database IN THE SAME TRANSACTION
  - [x] Store it in the cache
  - [x] Close all submenus
  - [Obsolete?] Refresh Vnlistfragment to make sure the new version is used in the list.
  - [x] Recreate activity
