### ISSUE TITLE
[Todo] Updating local data

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#7]
- [x] Remove the use of loadData() when leaving a VN details view after a "set" action.
- [x] Update the local data at the same time we send each "set" action to VNDB.
- [x] Set up a "refresh" action when pulling down a VN list that calls loadData().
