### ISSUE TITLE
[Todo] Improve screenshots viewing

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#76]
- [x] Horizontal layout (rather than vertical)
- [x] Enable zoom
- [x] Move to next/previous by swiping
- [x] Fullscreen ("cinema") mode
- [x] Display the number of screenshots.
- [ ] Download / Share / whatever action buttons somewhere in a hidable toolbar.

**Comment by herbeth1u** [comment]
http://www.androidhive.info/2013/09/android-fullscreen-image-slider-with-swipe-and-pinch-zoom-gestures/

**Comment by herbeth1u** [comment]
Write something based on this?
https://github.com/VEINHORN/ScrollGalleryView/tree/master/library/src/main/java/com/veinhorn/scrollgalleryview

**Comment by herbeth1u** [comment]
https://github.com/chrisbanes/PhotoView in a ViewPager :)

**Comment by herbeth1u** [comment]
https://github.com/ccrama/Slide/blob/master/app/src/main/java/me/ccrama/redditslide/Notifications/ImageDownloadNotificationService.java#L219
