### ISSUE TITLE
[Todo] Redesign stats page 

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#85]
- [ ] Move stats item at the bottom of the drawer. 
- [ ] Create a "My stats" + "DB stats" page layout. 
- [ ] Use card views and MPAndroidChart to show stats. 
- [ ] Use user info to infer user stats (cf VNStat for ideas or check VNStat's Users API if too complex to implement) :
  - You've played between x and y hours in total (use length of all games) 
  - You've played x games tagged a (tags ranking) 
  - Create a user level based on the number of games played and which would increase following a logarithmic or square root function? :)
