### ISSUE TITLE
[Todo] Preferences

### ISSUE THREAD

**Issue by herbeth1u** [herbeth1u/VNDB-Android#9]
- [ ] Long press to copy an element's text to clipboard -> not disturbing atm.
- [x] Theme selection
- [x] Hide spoilers by default yes/no.
  - [x] If yes : auto show spoilers when status = completed
- [x] Hide NSFW by default yes/no.
- [ ] Search button in action bar or in badge? -> will stay in badge for the moment because it's more logic from a UX point of view.
